_G.Logging = {
	warning = function (...) end
}

dofile("scripts/TramlineWidthChecker.lua")

describe("Tramline Width Checker", function()
	it("allows 12m for a 12m tramline", function()
		assert.truthy(TramlineWidthChecker.workWidthIsCompatible(12, 12, 0))
	end)
	it("allows 4m for a 12m tramline", function()
		assert.truthy(TramlineWidthChecker.workWidthIsCompatible(4, 12, 0))
	end)
	it("does not allow 24m for a 12m tramline", function()
		assert.falsy(TramlineWidthChecker.workWidthIsCompatible(24, 12, 0))
	end)
	it("does not crash on stupid values", function()
		assert.has_no.errors(function() TramlineWidthChecker.workWidthIsCompatible("a", -24142151, .1251234125) end)
	end)
	it("does not run endlessly on negative values", function()
		assert.has_no.errors(function() TramlineWidthChecker.workWidthIsCompatible(-5, 24, 0) end)
	end)
	it("allows 2.4m for a 12m tramline with zero tolerance", function()
		assert.truthy(TramlineWidthChecker.workWidthIsCompatible(2.4, 12, 0))
	end)
	it("does not allow 3.4m for a 24m tramline with zero tolerance", function()
		assert.falsy(TramlineWidthChecker.workWidthIsCompatible(3.4, 24, 0))
	end)
	it("allows 3.4m for a 24m tramline with a .2 meter tolerance", function()
		assert.truthy(TramlineWidthChecker.workWidthIsCompatible(3.4, 24, 0.2))
	end)
	it("always returns false for zero values", function()
		assert.falsy(TramlineWidthChecker.workWidthIsCompatible(0, 0, 0))
	end)
end)